version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # Puerto de RabbitMQ para conexiones de la aplicación
      - "15672:15672"    # Puerto de la interfaz de administración web
    environment:
      RABBITMQ_DEFAULT_USER: user      # Cambia esto por tu usuario
      RABBITMQ_DEFAULT_PASS: password  # Cambia esto por tu contraseña

  django_app:
    build:
      context: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
